#include "gpu.h"

#define CL_TARGET_OPENCL_VERSION 120
#include <CL/cl.h>

#include <map>
#include <mutex>
#include <vector>

#include "log.h"

namespace {

// reframe_kernel.h as a string, generated by tools/embed.ps1 at build time
const char* kSource =
#include "reframe_kernel_cl.inc"
    ;

struct ContextState
{
    bool built = false;
    std::string buildError;
    cl_program program = nullptr;
    cl_kernel kernel = nullptr;
    cl_mem buf[2] = {nullptr, nullptr};
    size_t size[2] = {0, 0};
    cl_mem steps = nullptr;
    int stepCap = 0;
    uint64_t last[2] = {0, 0};  // serials of the frames currently on the device
};

std::mutex g_Mutex;
std::map<cl_context, ContextState> g_Contexts;

bool check(cl_int e, const char* what, std::string* err)
{
    if (e == CL_SUCCESS) return true;
    if (err) *err = std::string(what) + " failed (OpenCL error " + std::to_string(e) + ")";
    return false;
}

bool ensureKernel(ContextState& st, cl_context ctx, cl_device_id dev, std::string* err)
{
    if (st.built) return st.kernel != nullptr || (err && (*err = st.buildError, false));
    st.built = true;
    cl_int e;
    st.program = clCreateProgramWithSource(ctx, 1, &kSource, nullptr, &e);
    if (!check(e, "clCreateProgramWithSource", &st.buildError))
    {
        if (err) *err = st.buildError;
        return false;
    }
    e = clBuildProgram(st.program, 1, &dev, "-cl-mad-enable", nullptr, nullptr);
    if (e != CL_SUCCESS)
    {
        size_t n = 0;
        clGetProgramBuildInfo(st.program, dev, CL_PROGRAM_BUILD_LOG, 0, nullptr, &n);
        std::string log(n, '\0');
        clGetProgramBuildInfo(st.program, dev, CL_PROGRAM_BUILD_LOG, n, log.data(), nullptr);
        st.buildError = "OpenCL build failed: " + log;
        logf("%s", st.buildError.c_str());
        if (err) *err = st.buildError;
        return false;
    }
    st.kernel = clCreateKernel(st.program, "ReframeKernel", &e);
    if (!check(e, "clCreateKernel", &st.buildError))
    {
        st.kernel = nullptr;
        if (err) *err = st.buildError;
        return false;
    }
    return true;
}

} // namespace

bool openclRender(void* queuePtr, const RfParams* p, int n, const std::shared_ptr<const Nv12Frame>& s0,
                  const std::shared_ptr<const Nv12Frame>& s1, void* dst, std::string* err)
{
    cl_command_queue q = static_cast<cl_command_queue>(queuePtr);
    cl_context ctx = nullptr;
    cl_device_id dev = nullptr;
    if (!check(clGetCommandQueueInfo(q, CL_QUEUE_CONTEXT, sizeof(ctx), &ctx, nullptr), "queue context", err)) return false;
    if (!check(clGetCommandQueueInfo(q, CL_QUEUE_DEVICE, sizeof(dev), &dev, nullptr), "queue device", err)) return false;

    std::lock_guard<std::mutex> lock(g_Mutex);
    ContextState& st = g_Contexts[ctx];
    if (!ensureKernel(st, ctx, dev, err)) return false;

    const std::shared_ptr<const Nv12Frame>* frames[2] = {&s0, &s1};
    for (int i = 0; i < 2; ++i)
    {
        const Nv12Frame& f = **frames[i];
        size_t bytes = f.data.size();
        if (st.size[i] < bytes)
        {
            if (st.buf[i]) clReleaseMemObject(st.buf[i]);
            st.buf[i] = nullptr;
            st.size[i] = 0;
            st.last[i] = 0;
            cl_int e;
            st.buf[i] = clCreateBuffer(ctx, CL_MEM_READ_ONLY, bytes, nullptr, &e);
            if (!check(e, "clCreateBuffer", err)) { st.buf[i] = nullptr; return false; }
            st.size[i] = bytes;
        }
        if (st.last[i] != f.serial)
        {
            if (!check(clEnqueueWriteBuffer(q, st.buf[i], CL_TRUE, 0, bytes, f.data.data(), 0, nullptr, nullptr), "upload", err))
                return false;
            st.last[i] = f.serial;
        }
    }

    if (st.stepCap < n)
    {
        if (st.steps) clReleaseMemObject(st.steps);
        st.stepCap = 0;
        cl_int e;
        st.steps = clCreateBuffer(ctx, CL_MEM_READ_ONLY, sizeof(RfParams) * n, nullptr, &e);
        if (!check(e, "clCreateBuffer", err)) { st.steps = nullptr; return false; }
        st.stepCap = n;
    }
    if (!check(clEnqueueWriteBuffer(q, st.steps, CL_TRUE, 0, sizeof(RfParams) * n, p, 0, nullptr, nullptr), "upload params", err))
        return false;

    cl_mem out = static_cast<cl_mem>(dst);
    cl_int e = clSetKernelArg(st.kernel, 0, sizeof(cl_mem), &st.steps);
    e |= clSetKernelArg(st.kernel, 1, sizeof(int), &n);
    e |= clSetKernelArg(st.kernel, 2, sizeof(cl_mem), &st.buf[0]);
    e |= clSetKernelArg(st.kernel, 3, sizeof(cl_mem), &st.buf[1]);
    e |= clSetKernelArg(st.kernel, 4, sizeof(cl_mem), &out);
    if (!check(e, "clSetKernelArg", err)) return false;
    size_t local[2] = {16, 16};
    size_t global[2] = {size_t((p[0].outW + 15) / 16 * 16), size_t((p[0].outH + 15) / 16 * 16)};
    if (!check(clEnqueueNDRangeKernel(q, st.kernel, 2, nullptr, global, local, 0, nullptr, nullptr), "kernel launch", err))
        return false;
    // The source buffers are shared between renders that may use different queues: finish before unlocking.
    return check(clFinish(q), "kernel", err);
}

bool openclCopy(void* queuePtr, void* dst, const void* src, size_t bytes, bool fromHost, std::string* err)
{
    cl_command_queue q = static_cast<cl_command_queue>(queuePtr);
    cl_mem d = static_cast<cl_mem>(dst);
    cl_int e = fromHost ? clEnqueueWriteBuffer(q, d, CL_TRUE, 0, bytes, src, 0, nullptr, nullptr)
                        : clEnqueueCopyBuffer(q, static_cast<cl_mem>(const_cast<void*>(src)), d, 0, 0, bytes, 0, nullptr, nullptr);
    if (!check(e, "copy", err)) return false;
    return check(clFinish(q), "copy", err);
}
